# Site settings
title: Daniel Fosco
email: danielfosco@gmail.com
description: "Portfolio of Daniel Fosco"
production_url: http://dfosco.github.io/v2
BASE_PATH : http://dfosco.github.io/v2
ASSET_PATH : /v2/assets

exclude: [/links/source]

# Author settings
author:
 name: Daniel Fosco
 twitter_username: notdanielfosco
 github_username:  dfosco

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title

